image: docker:latest
services:
  - docker:dind

stages:
  - pre_deploy
  - deploy

pre_deploy:
  stage: pre_deploy
  script:
          - echo 'Running with'
          - echo $KUBE_URL

deploy:
  stage: deploy
  image: dtzar/helm-kubectl
  script:
    - echo "$KUBE_CA_PEM_FILE" > "$(pwd)/kube.ca.pem"
    - kubectl config set-cluster k8s --server="${KUBE_URL}" --certificate-authority="$(pwd)/kube.ca.pem"
      #- kubectl config set clusters.k8s.certificate-authority-data "$(pwd)/kube.ca.pem"
    - kubectl config set-credentials gitlab --token="${KUBE_TOKEN}"
    - kubectl config set-context default --cluster=k8s --user=gitlab
    - kubectl config use-context default
    #- sed -i "s/<VERSION>/${CI_COMMIT_SHORT_SHA}/g" deployment.yaml
    - kubectl delete -f nginx-deployment.yaml
