- name: Set Home Folder
  set_fact:
     HOME_FOLDER: "{{ lookup('env','HOME') }}"


- name: Copy Spinnaker account files
  copy:
    src:  "{{ SPINNAKER_ACCT_FILE }}"
    dest: "{{ HOME_FOLDER }}"/spinacct.yaml
    owner: labadmin
    group: labadmin
    mode: '0644'


- name: Create Spinnaker Account
  command: kubectl create -f "{{ HOME_FOLDER }}"/spinacct.yaml


- name: Create Spinnaker namespace
  command: kubectl create namespace spinnaker


- name: Copy Spinnaker services files
  copy:
    src:  "{{ SPINNAKER_SVC_FILE }}"
    dest: "{{ HOME_FOLDER }}"/spinsvc.yaml
    owner: labadmin
    group: labadmin
    mode: '0644'


- name: Create Spinnaker Service
  command: kubectl create -f "{{ HOME_FOLDER }}"/spinsvc.yaml


- name: Getting Halyard installation script
  get_url:
     url: "{{ HALYARD_INSTALLATION_SCRIPT }}"
     dest: "{{ HOME_FOLDER }}/InstallHalyard.sh"
     mode: 0440


- name: Running Halyard instalaltion script
  command: "bash {{ HOME_FOLDER }}/InstallHalyard"
  become: true
