---
- name: install APT Transport HTTPS
  apt:
    name: apt-transport-https
    state: present
  become: true

- name: Adding Kubernetes gpg key
  apt_key:
    url: "{{ K8S_GPG_KEY }}"
    state: present
  become: true


- name: Adding kubernetes APT repository
  apt_repository:
    repo: "{{ K8S_REPO }}"
    state: present
    filename: kubernetes.list
    update_cache: yes
  become: true


- name: Installing Kubenertes (kubelet, kubeadm, kubectl) binaries
  apt:
    name: "{{ K8S_PACKAGES }}"
    state: present
    update_cache: yes
  become: true


- name: Disable swap file
  command: swapoff -a
  become: true


- name: Remove swap file from /etc/fstab
  mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
  with_items:
      - swap
      - none
  become: true


  #- name: Restart kubelet
  #  service:
  #      name: kubelet
  #      daemon_reload: yes
  #      state: restarted
  #  become: true
