---
- hosts: all
  gather_facts: yes
  become: yes
  roles:
    - role: docker
    - role: kube

- hosts: master
  gather_facts: yes
  roles:
    - role: kube_master
      #- role: helm

- hosts: workers
  gather_facts: yes
  roles:
      - role: kube_worker
